export const MATH_QUOTES = [
  "Pure mathematics is, in its way, the poetry of logical ideas.",
  "Mathematics reveals hidden patterns that help us understand the world.",
  "The essence of mathematics lies in its freedom.",
  "Go down deep enough into anything and you will find mathematics.",
  "Mathematics is the music of reason.",
  "There is no royal road to geometry.",
  "In mathematics, the art of proposing a question must be held of higher value than solving it.",
  "Mathematics knows no races or geographic boundaries.",
  "Life is good for only two things: discovering mathematics and teaching mathematics.",
  "Mathematics compares the most diverse phenomena and discovers the secret analogies that unite them.",
  "The only way to learn mathematics is to do mathematics.",
  "You do not really understand mathematics unless you can explain it simply.",
  "A problem well stated is a problem half solved.",
  "Every theorem begins as a question someone refused to ignore.",
  "Small steps in mathematics still move you forward.",
  "Understanding beats memorizing every single time.",
  "A hard proof today becomes intuition tomorrow.",
  "Each solved problem sharpens the next idea.",
  "Confusion is often the first sign of real learning.",
  "Mathematics rewards patience with clarity.",
  "A neat diagram can save an hour of struggle.",
  "The answer matters, but the method matters more.",
  "In maths, persistence is a superpower.",
  "The page looks less intimidating after the first line.",
  "Every elegant solution started as a messy attempt.",
  "A blank page is just the start of a proof.",
  "Patterns appear for those who stay with the problem.",
  "You are closer than you think after every honest attempt.",
  "One extra practice question changes more than you expect.",
  "Theorems are tools, not decorations.",
  "The hardest part is often staying in the question long enough.",
  "Math grows when you revisit what once felt impossible.",
  "A proof is a conversation between logic and curiosity.",
  "You learn more from checking your steps than from rushing the result.",
  "Progress in math often feels slow right before it becomes obvious.",
  "Mastery is built from many quiet repetitions.",
  "There is beauty in a well-placed substitution.",
  "A difficult concept becomes manageable when broken into parts.",
  "Math is less about speed and more about structure.",
  "Keep going until the symbols start telling a story.",
  "The next insight usually arrives after the next attempt.",
  "Good habits solve more problems than last-minute motivation.",
  "One clear definition can unlock an entire topic.",
  "Strong foundations make advanced topics feel lighter.",
  "Precision is kindness to your future self.",
  "In mathematics, details are where understanding lives.",
  "A cleaner setup often produces a cleaner answer.",
  "Every topic gets easier the moment its language becomes familiar.",
  "You are not behind; you are building fluency.",
  "Math confidence is earned one solved question at a time.",
  "Questions are evidence that your mind is working.",
  "The best revision is active, messy, and honest.",
  "A mistake caught early is a lesson remembered longer.",
  "There is momentum in showing up to practice again.",
  "Proof by patience works more often than people admit.",
  "You do not need magic, only another careful pass.",
  "The difference between stuck and solved is often one new viewpoint.",
  "A worked example is a bridge, not a crutch.",
  "Mathematics becomes friendlier when you stop trying to do it all at once.",
  "Focus on the next logical step, not the whole mountain.",
  "A single definition can change the way an entire chapter feels.",
  "The mind grows stronger in the middle of difficult problems.",
  "Progress in calculus is made line by line.",
  "Linear algebra rewards people who organize their thoughts.",
  "Real understanding starts when you ask why a method works.",
  "The graph often knows what the algebra is trying to say.",
  "Symbols are intimidating only until they become familiar.",
  "Learning mathematics is learning how to stay curious under pressure.",
  "The proof is long, but so is your patience.",
  "Practice turns strange notation into ordinary language.",
  "You can trust slow, careful reasoning.",
  "Every revision session leaves a trace, even when it feels small.",
  "Math gets better when you write more and guess less.",
  "A problem solved twice is a concept remembered longer.",
  "When in doubt, return to the definition.",
  "The shortest route to confidence is consistent practice.",
  "Hard questions are often invitations to think more deeply.",
  "Your future understanding is built by today's scratch work.",
  "Even elegant solutions begin with rough notes.",
  "Clarity is often hiding inside the simplest case.",
  "A theorem is easier to remember once you have used it.",
  "The best time to slow down is when the algebra gets fast.",
  "Math is a craft; fluency comes from use.",
  "A solved example becomes your vocabulary for the next challenge.",
  "You do not need to know everything; you need to know what to do next.",
  "There is strength in reworking a question until it feels natural.",
  "Discipline makes difficult topics less dramatic.",
  "One more derivation can turn confusion into structure.",
  "If you can draw it, you can often understand it.",
  "If you can explain it aloud, you probably own it.",
  "A strong setup makes the computation feel lighter.",
  "Mathematics favors students who return to it regularly.",
  "A hard exercise is still progress if it made you think.",
  "The route to elegance usually passes through rough drafts.",
  "Each chapter becomes smaller after the first serious review.",
  "Mathematics is learned by contact, not by proximity.",
  "A careful rewrite can be the difference between panic and understanding.",
  "Consistency beats intensity in almost every topic.",
  "Every formula becomes useful when tied to a picture or idea.",
  "The problem is not bigger than your ability to break it down.",
  "Study until the method feels inevitable.",
  "Stay with the symbols long enough and they become intuitive.",
  "What feels advanced today becomes standard with repetition.",
  "Good mathematics is built from attention, not luck.",
  "A difficult week in math is still a week of growth.",
  "Keep solving until confidence starts sounding like logic.",
  "There is always another way to look at the same problem.",
] as const;
